### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [livegrep/livegrep#179]
Would you like to add more error handling for return values from functions like the following?
- [pthread_key_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_key_create.html "Thread-specific data key creation") ⇒ [per_thread constructor](https://github.com/livegrep/livegrep/blob/fee2a0cc07f4f643aaba412549dd3e0d8f22867b/src/lib/per_thread.h#L16)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [analyze_re](https://github.com/livegrep/livegrep/blob/fee2a0cc07f4f643aaba412549dd3e0d8f22867b/src/tools/analyze-re.cc#L113)

**Comment by nelhage** [comment]
I'm not interested in checking the return values from `printf`. I wouldn't mind `assert`s so that we fast-fail if `pthread_key_create` fails.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
