### ISSUE TITLE
Version of grpc being used?

### ISSUE THREAD

**Issue by staktrace** [livegrep/livegrep#182]
How can I tell what version of grpc is being used when I build livegrep? I'm not too familiar with how the golang repositories work. The output I see when building contains this:

```
Downloading https://github.com/grpc/grpc/archive/ca87867579580928ca4c9fdf97051fa25bf1d386.zip via codeload.github.com: 4,818,944 bytes
```

but that's a really old version and doesn't correspond to any tagged release in the grpc repository. I also see other output that indicates it's downloading grpc from the golang repos but there's no versioning there.

The larger context around my question is that I'm querying the livegrep server from some python code which using `grpcio==1.14.1` and getting some deserialization errors that I suspect are version mismatches. But I don't know which version to use on the python side because I can't tell what version is being used to serialize on the livegrep side. Help would be appreciated, thanks!

**Comment by nelhage** [comment]
That URL is probably right … grpc is pulled in using bazel via a source dependency buried somewhere in a dependency. Those are long overdue for some updates for newer versions of everything. I'll keep this open as a request to bump dependencies :)

**Comment by nelhage** [comment]
Let me know if that solves your problem! Thanks for opening the issue.

**Comment by staktrace** [comment]
Unfortunately not; I'm still getting the deserialization error. I'll try to debug it.
