### ISSUE TITLE
file: modifier occasionally produces incorrect results

### ISSUE THREAD

**Issue by tpcwang** [livegrep/livegrep#20]
The file modifier does not always return the correct results. Try running the following queries a few times and you should see that the results differ occasionally:
https://livegrep.com/search/linux?q=fatal+file%3A%5C.tmpl
https://livegrep.com/search/linux?q=open+file%3Ath%5C.c

(By the way, thank you for livegrep!)

**Comment by nelhage** [comment]
Fascinating. Those searches are giving truncated results because they're hitting an internal resource-consumption timeout. I should probably bump that timeout, which will alleviate the issue, but what I don't understand is why they exhibit such bimodal performance. I'll try to dig into that today.

**Comment by nelhage** [comment]
I've bumped the timeout and tuned the number of threads in prod. Working on some further improvements now…

**Comment by tpcwang** [comment]
Cool! It might be a good idea to report an error to the user somehow when a timeout does occur, sort of like the regex error. This will be a signal for them to tune their query without relying on the state of the deployed system, the timeout value and possibly the repo size. This is not a big deal though, as most queries probably won't hit the timeout.

**Comment by nelhage** [comment]
Yeah, I'll ponder. It was originally intended as an abuse-protection mechanism, with the intent that ~no real query should run into it, and I didn't want to make it obvious what was going on. In retrospect, abuse hasn't been a problem at all, and it occasionally trips people up.

The other thing that's going on is that I recently rebuilt livegrep.com into EC2, and there are some performance problems I don't fully understand running on the new hardware, that I'm still investigating.

Glad you find the tool useful, and thanks for the report.

**Comment by nelhage** [comment]
btw, if you're curious, I'm pretty sure that https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457 is what's causing performance problems. I'm going to downgrade livegrep.com to an older kernel some time this weekend, hopefully, which I expect will improve the situation.

**Comment by tpcwang** [comment]
Interesting. Hope that's the problem!
