### ISSUE TITLE
Feature request: add repo support for other VCS through fs_paths

### ISSUE THREAD

**Issue by tpcwang** [livegrep/livegrep#21]
My use case is that I want to index source code on various VCS with other source browsers that I have already set up. I don't think livegrep should add support for those VCS, but it would be nice to indirectly support them through the file indexer. I think the following tasks will be necessary:
- [x] Expand fspaths from arrays of strings to arrays of objects with similar structure as repositories
- [x] Support rendering links using a custom format (possibly plumbing metadata through the layers)

What are your thoughts? I'll look to see if I can implement it if you are okay with this approach.

**Comment by nelhage** [comment]
Yeah, I'd be happy to have this feature, and to take a PR of that form. Some sort of generic plumbing of custom formats through from the config to the web interface would be awesome, but something more hackish that supported keys other than `github` in the metadata would also be fine for now.
