### ISSUE TITLE
Build failure on latest code

### ISSUE THREAD

**Issue by staktrace** [livegrep/livegrep#218]
I'm trying to build `codesearch` the way I have done so successfully in the past, using bazel-0.16.1:

```
bazel build //src/tools:codesearch --spawn_strategy=standalone --genrule_strategy=standalone
```

However this produces an error when run on master:

```
ERROR: /home/vagrant/livegrep/src/proto/BUILD:32:1: undeclared inclusion(s) in rule '//src/proto:cc_proto':
this rule is missing dependency declarations for the following files included by 'src/proto/cc_proto_pb/src/proto/config.pb.cc':
  'bazel-out/k8-fastbuild/genfiles/src/proto/config.pb.h'
Target //src/tools:codesearch failed to build
INFO: Elapsed time: 251.949s, Critical Path: 23.86s
INFO: 330 processes: 330 local.
FAILED: Build did NOT complete successfully
```

I'm not too familiar with bazel so it's not clear to me what the problem is.

**Comment by nelhage** [comment]
Hm, are you able to try with a newer bazel? We test on 0.22 in CI, and it works in 0.21 locally.

If that's not an option or if it's still broken there in your environment, I may be able to take a look.

**Comment by staktrace** [comment]
You may want to update the README.md which says "0.3 or newer" is fine :)

But even so, I tried using 0.22 and it gave me a different error: https://gist.github.com/staktrace/19e7da7b9b73f5731db856980f9f9c08 - do I need to have particular compiler versions? The `/usr/bin/gcc` that's being invoked is `Ubuntu 5.4.0-6ubuntu1~16.04.10`

**Comment by nelhage** [comment]
I've been busy so I haven't had a chance to investigate, but I do suspect that this could be a compiler version problem. Is using a newer GCC easy to try?

I'll do some digging and update the README at some point hopefully this week.

If it turns out to be a compiler version problem, I might try vendoring a CROSSTOOL that would (optionally) download+use a specified pinned clang version; That should improve reproducibility, at the cost of downloading a few hundred MB during first build.

**Comment by nelhage** [comment]
It builds fine for me using a bare `bazel build` on Bazel 0.22 and GCC 5.4.0-6ubuntu1~16.04.11 in an `ubuntu:16.04` docker image.

However, I can reproduce a failure using `--spawn_strategy=standalone --genrule_strategy=standalone`. Do you remember why you added those to your command line? I can try to debug why they break, but are you able to test building without those options in your environment?

**Comment by staktrace** [comment]
Those arguments are from before I inherited the code, but there's this comment next to them: https://github.com/mozsearch/mozsearch/blob/master/infrastructure/indexer-provision.sh#L60

```
# The last two options turn off the bazel sandbox, which doesn't work
# inside an LDX container.
```

I presume the "LDX container" being referred to is related to the fact that we're deploying to AWS instances.

**Comment by staktrace** [comment]
I can try removing those options and see if it still works though. Will report back.

**Comment by nelhage** [comment]
I *think* bazel has changed how sandboxing works since the old versions so I'm hopeful that it will work better (I speculate that "LDX" is a typo for [LXD containers[(https://linuxcontainers.org/lxd/introduction/), and I believe that the bazel sandbox now works inside containers).

I do think that the build _should_ work even with the standalone executors, so I'll take a look when I have some time; It should be fixable given that I have a reproducer.

**Comment by staktrace** [comment]
Using bazel 0.22.0 and `bazel build //src/tools:codesearch` gave me this:

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 847c4c9b-f0b3-4a19-89b9-80a9d5ee97f5
Loading:
Loading: 0 packages loaded
DEBUG: Rule 'com_github_nelhage_rules_boost' modified arguments {"shallow_since": "1534175467 -0700"}
Loading: 0 packages loaded
DEBUG: Rule 'io_bazel_rules_go' modified arguments {"shallow_since": "1535226085 -0400"}
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: Rule 'org_pubref_rules_protobuf' modified arguments {"shallow_since": "1523370139 -0600"}
DEBUG: Rule 'org_dropbox_rules_node' modified arguments {"shallow_since": "1532824647 -0700"}
Analyzing: target //src/tools:codesearch (1 packages loaded, 0 targets configured)
Analyzing: target //src/tools:codesearch (4 packages loaded, 16 targets configured)
Analyzing: target //src/tools:codesearch (4 packages loaded, 16 targets configured)
Analyzing: target //src/tools:codesearch (4 packages loaded, 16 targets configured)
Analyzing: target //src/tools:codesearch (4 packages loaded, 16 targets configured)
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/63fc5f63aa116a29bd7b9561380973dc/external/go_sdk/BUILD.bazel:52:1: no such target '@io_bazel_rules_go//go:toolchain': target 'toolchain' not declared in package 'go'; however, a source directory of this name exists.  (Perhaps add 'exports_files(["toolchain"])' to go/BUILD, or define a filegroup?) defined by /home/ubuntu/.cache/bazel/_bazel_ubuntu/63fc5f63aa116a29bd7b9561380973dc/external/io_bazel_rules_go/go/BUILD.bazel and referenced by '@go_sdk//:go_linux_arm'
ERROR: While resolving toolchains for target //src/tools:codesearch: invalid registered toolchain '@go_sdk//:go_linux_arm': Analysis failed
ERROR: Analysis of target '//src/tools:codesearch' failed; build aborted: Analysis failed
INFO: Elapsed time: 19.444s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (9 packages loaded, 35 targets configured)
FAILED: Build did NOT complete successfully (9 packages loaded, 35 targets configured)
```

**Comment by nelhage** [comment]
Huh, I've never seen that I can't reproduce. It seems to [match a bug report on `rules_go`](https://github.com/bazelbuild/rules_go/issues/1752), though, so I've upgraded `rules_go` on master -- any luck there?

**Comment by staktrace** [comment]
Sorry for the delay. But yes - with the master version of livegrep and bazel 0.22 I was able to build on AWS without the `standalone` argument stuff. Thanks! I think this issue can be closed now, I'll proceed with testing my patch for #216
