### ISSUE TITLE
[Livegrep Github Reindex] Git Clone over https not working for private repositories

### ISSUE THREAD

**Issue by markomafs** [livegrep/livegrep#223]
## What? 

When running `livegrep-github-reindex` script using `-github-token` and `-http` flag: 
* it is fetching a list of repositories as expected.
* but when is trying to clone it, asks for username/password. 

## Why?  

There is no implementation of tokens on clone code neither a GH(github) client injection with oauth http client.

**Comment by regularfry** [comment]
Any chance of a docker image build with this fix in it?  The most recent published version is [this one|https://hub.docker.com/layers/livegrep/indexer/fafe1b95ff-0/images/sha256-84ebf38acb09c721771191f497548c6982530090b583c935791cfef20325e137], which predates this fix.

**Comment by nelhage** [comment]
I've just pushed a build for https://hub.docker.com/layers/livegrep/indexer/latest/images/sha256-aec76fc7a09ec33a66847458bc9003735449ac7d171eff51590362c416f1cd7f which should contain 75b59048dfa80ea4309f12515be54eb9cc66774d

**Comment by regularfry** [comment]
Brilliant, thank you.
