### ISSUE TITLE
Pie-in-the-sky feature request: searching for definitions using ctags results

### ISSUE THREAD

**Issue by tpcwang** [livegrep/livegrep#23]
Let me first say that this possibly falls outside of what livegrep should reasonably do, but I'll throw it out there and see what you think.

It is great that livegrep can search for any text in the code, just like plain old grep, but I often have a symbol and I just want to go to the definition quickly. This can be troublesome for symbols that are common, such as [open](https://livegrep.com/search/linux?q=open). It is arguable that the user should craft a better regex to narrow down the search, such as [int.*open\\( file:\\.c](https://livegrep.com/search/linux?q=int.*open%5C\(+file%3A%5C.c), but I wonder if we can do better than that.

One possibility is to implement an indexer that uses the output of ctags and only add the tag name to the suffix array instead of entire lines. If we can maintain the line context, then users who want to search for symbols can search for it in the "tags" repo and the results will only contain definitions.

Another possibility is to implement a different backend that implements its own mechanism using the tags file for returning the results to the frontend.

Is this outside the scope of livegrep?

**Comment by tpcwang** [comment]
Looking through the code, I think possibility 1 will muddy the implementation too much due to the way that the line context and the match results are constructed. Feel free to close this issue if you think possibility 2 doesn't belong in livegrep.

**Comment by nelhage** [comment]
Yeah, I suspect this doesn't make sense as a baked-in thing in livegrep. I'd potentially be interested in frontend support for plugging into some other backend that runs side-by-side with the backend, but I don't have any particular thoughts on the shape of that.

**Comment by tpcwang** [comment]
Fair enough. Thanks for the consideration!
