### ISSUE TITLE
livegrep-github-reindex error when repo is empty

### ISSUE THREAD

**Issue by vcabbage** [livegrep/livegrep#237]
I ran into a situation where `livegrep-github-reindex` fails to update repos when one of the repos is empty (as in newly created in github). 

The initial pull completes with a notice that the repo may be empty.  On the next execution the process exits with an error like:
```
fatal: Couldn't find remote ref HEAD
... other output ...
git [--git-dir /path/to/repo fetch -p origin +HEAD:HEAD +refs/*:refs/*]: exit status 128
```

This results in some of the repos not being update and the index not being rebuilt. I don't know if there's a reasonable way to handle checking for this situation, but perhaps failure to update an individual repo should be changed to non-fatal?

Thank you for your work on this project! It's an immensely helpful tool!

**Comment by nelhage** [comment]
Oof, this is frustrating. This is fallout of https://github.com/livegrep/livegrep/pull/222, but I think I may want to just revert that, since on further testing it doesn't quite work; specifically, it ends up creating a new `refs/heads/HEAD` ref, which sorta-works but really isn't what you want…
