### ISSUE TITLE
'CXXABI_1.3.11 not found' running livegrep-github-reindex

### ISSUE THREAD

**Issue by bgrainger** [livegrep/livegrep#245]
I'm attempting to run the livegrep/indexer Docker container:

```
docker run -it --name=livegrep-index -v [data]  -v [repos] livegrep/indexer:latest /bin/bash
```

When I execute `/livegrep/bin/livegrep-github-reindex` it successfully clones/updates all the repos, but then errors with:

```
/livegrep/bin/codesearch: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /livegrep/bin/codesearch)
/livegrep/bin/codesearch: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /livegrep/bin/codesearch)
```

Could this be because the CircleCI image is [built from](https://github.com/livegrep/livegrep/blob/master/.circleci/Dockerfile#L1) `ubuntu:18.04`, but the runtime livegrep/base image is [built from](https://github.com/livegrep/livegrep.com/blob/master/docker/base/Dockerfile#L1) `ubuntu:16.04`?

**Comment by nelhage** [comment]
Whoops, yep, looks like your diagnosis is exactly right. I just pushed a bump that I think should fix once it builds+pushes.
