### ISSUE TITLE
Proposal: repository tags in metadata

### ISSUE THREAD

**Issue by LINKIWI** [livegrep/livegrep#248]
I'd like to propose the addition of a new repeated string field `tags` to the `Metadata` message: https://github.com/livegrep/livegrep/blob/5c916f5eb1001c6325742ca90d7dda32a1df52bb/src/proto/config.proto#L9

The use case would be to associate arbitrary labels to a repository spec, so that livegrep clients could group several repositories together in a semantically meaningful way. The client could, for example, use these tags to aggregate an array of repositories to search from. This would be particularly useful in a deployment where livegrep indexes hundreds of repositories, and you might want to e.g. search across all repositories tagged with `language-go`.

For example, if repository specs are tagged as follows,

```
repos: [
    RepoSpec{..., metadata: Metadata{..., tags: ["language-python", "internal"]}},
    RepoSpec{..., metadata: Metadata{..., tags: ["language-go", "internal"]}},
    RepoSpec{..., metadata: Metadata{..., tags: ["language-javascript", "oss"]}},
]
```

A call to `Info()` RPC might return something like this:

```
...
trees: [
    ...
    Tree{
        url_pattern: "https://github.com"
        remote: "git@github.com:eslint/eslint.git"
        tags: ["language-javascript", "oss"]
    }
]
```

Looks like the server-side code is already capable of persisting and retrieving arbitrary structured data from the `metadata` field, so this only requires a simple change to the Protobuf schema.

Also, `tags` might be a bit confusing since it is unrelated to the ctags support. Maybe a different name would be better, like `labels` or something to that effect.

**Comment by nelhage** [comment]
This makes sense to me! I agree that "tags" would collide with the `ctags` support, so I like `labels`. Are you up for sending over a PR? I believe you are correct that this should be a simple change to the protobufs.

**Comment by LINKIWI** [comment]
Thanks for the response. I'll send over a PR later today. It should be a simple change. Thanks!
