### ISSUE TITLE
I get a warning for 93MB ASCII Text file 

### ISSUE THREAD

**Issue by Manoj321** [livegrep/livegrep#25]
I have written a small scripts based on src/tools/codesearch.cc to index a single file without any changes to the defaults in codesearch.cc. I'm able to index small files ( <10MBs ) and search works as expected. 

Test Script Pseudo code:

```C++
search->set_alloc( make_mem_allocator() );
fs_indexer indexer(search, path , name, 0 ); 
indexer.read_file( path ); 
search->finalize();
```

The problem is with slightly larger files( 90MB ). After stepping through the code I found that the code was returning at this point in code_searcher::index_file function: 

```C++
if (memchr(p, 0, len) != NULL){
       return; 
}
```
After commenting this part I was able to index the 90MB file with a warning that the file is too big. Following are the metrics. 

Metrics:
```
Number of lines: 627941 <-- I added this line
WARN: test:: is too large to be indexed.
indexed in 1.750006s
== begin metrics ==
index.bytes 97395291
index.bytes.dedup 80669472
index.content.chunks 1
index.content.ranges 0
index.data.chunks 1
index.files 1
index.lines 627941
index.lines.dedup 499911
timer.git.walk 0
timer.index.dedup.hash 315
timer.index.divsufsort 7977
timer.index.fixupnl 118
timer.index.index_file 1505
== end metrics ==
Result Size: 0
```
 I wasn't able to perform any searches on this even though the given string was present in the file.
Do I have to tweak some parameters to index big files?

**Comment by tpcwang** [comment]
Hm.. I don't think there are config tweaks to index big files. What you probably ran into is that codesearch fails to allocate a contiguous 90MB memory chunk to store the file content. Likely workaround would be to increase the RAM size if it's inside a VM or container, or run codesearch before memory fragmentation occurs if there should be enough memory.

@nelhage can give a more definitive answer.

**Comment by Manoj321** [comment]
I think memory is not the problem because I'm on a 128GB machine with ~50Gb free RAM.

**Comment by nelhage** [comment]
There's a ~hard-coded limit on the size of files it can index (with some fuzz because of how the content store is represented…). You could probably bump this constant: https://github.com/livegrep/livegrep/blob/ff3cb8f9c22e6fc70018eb81349d89611c5d3001/src/chunk_allocator.h#L96 and make it work.

If you can, breaking your file into chunks and indexing them separately is more in-line with how livegrep is designed to work.

**Comment by Manoj321** [comment]
Thanks you for quick reply.
I'll try breaking the file. 
Is there a recommended file size which best works with livegrep?  may be multiples of PAGESIZE ?

**Comment by nelhage** [comment]
There isn't a particular size that's optimal. The storage is line-based, so in many ways it depends on the number of lines in the file as much as the number of bytes. There are a few other oddities. I'd recommend some experimentation to figure out what works out well.

**Comment by Manoj321** [comment]
So I tried splitting a 1GB file into different sizes starting from 10M down to 100K bytes.
Every time the program terminated with bad_alloc exception.
Is there anything else I can try?

**Comment by nelhage** [comment]
Did you get a stack trace out of the `bad_alloc`? Are you able to share your test cases somewhere so I can try to reproduce?

Also, I note you mentioned commenting out this block:

```c
if (memchr(p, 0, len) != NULL){
       return; 
}
```

That's a check for NULL bytes in the file; livegrep filters out files with NULLs and assumes that indexed files have no NULL bytes, so if your corpus does contain NULLs, it's possible that's causing problems.

**Comment by Manoj321** [comment]
I have uncommented that block.
Here is the backtrace:
```
#0  0xf76efa30 in __kernel_vsyscall ()
(gdb) backtrace
#0  0xf76efa30 in __kernel_vsyscall ()
#1  0xf70995c7 in raise () from /lib/libc.so.6
#2  0xf709ae8a in abort () from /lib/libc.so.6
#3  0xf7315d65 in __gnu_cxx::__verbose_terminate_handler() ()
   from /lib/libstdc++.so.6
#4  0xf73138f6 in ?? () from /lib/libstdc++.so.6
#5  0xf7313970 in std::terminate() () from /lib/libstdc++.so.6
#6  0xf7313be3 in __cxa_throw () from /lib/libstdc++.so.6
#7  0xf7314274 in operator new(unsigned int) () from /lib/libstdc++.so.6
#8  0xf731431e in operator new[](unsigned int) () from /lib/libstdc++.so.6
#9  0x0804f476 in alloc_chunk (this=0x88bb180) at src/chunk_allocator.cc:140
#10 chunk_allocator::new_chunk (this=0x88bb180) at src/chunk_allocator.cc:96
#11 0x0804f680 in chunk_allocator::alloc (this=0x88bb180, len=209)
    at src/chunk_allocator.cc:66
#12 0x08057c94 in code_searcher::index_file (this=0xffca1b0c, tree=0x88bb3d8,
    path="xzefq", contents=...) at src/codesearch.cc:441
#13 0x08067a6b in fs_indexer::read_file (this=0xffca1a14, path=
    "/home/manojm321/livegrep/log/chunks/xzefq")
    at src/fs_indexer.cc:34
#14 0x0806834b in fs_indexer::walk (this=<optimized out>, path=...)
    at src/fs_indexer.cc:51
#15 0x0804dd24 in build_index (search=0xffca1b0c) at benchmark.cc:31
#16 0x0804d0bb in main (arg=1, argv=0xffca1c94) at benchmark.cc:39
```
Unfortunately, I cannot share the "xfeq" file.
Here is the code which I'm using.
http://pastebin.com/hHXX8sPW
Also I found out that my machine is 32bit!( actually machine is 64bit but chrooted workspace is 32 :/ ) I'll try this on a 64bit machine.

One more observations is that the RSS for this program reaches 2.2GB ( for a 797MB file! ) and then i get the bad_alloc exception. May be the index doesn't use same amount of memory as input files. I guess it is 5n + O(1)?

**Comment by nelhage** [comment]
The index can use up to 5n+O(1) memory; It does some compression that tends to shrink it to closer to the original on source code, but the effectiveness varies.

I suspect that your 32-bit machine is the problem, yeah.

**Comment by Manoj321** [comment]
So, I got livegrep working inside Docker. After increasing the chunk size to 2^32 I was able to index large files(upto 5GB) with out any problem. In my case unfortunately only big files had NULLs, which threw me off the track.
@nelhage May be you should throw some light on how resources are utilized in one of your blog posts :)
Also, I think I might be able to provide some performance numbers soon.
