### ISSUE TITLE
Select All results in HTTP 414

### ISSUE THREAD

**Issue by ptarjan** [livegrep/livegrep#259]
We have ~400 repos, and clicking Select All leaves the UI in a weird state that looks unresponsive. Worse yet, there seems to be a memory of the last repos you selected so users basically permanently break themselves.

Is there some mitigation we can put in for it somewhere?

![image](https://user-images.githubusercontent.com/40143/77943677-77cd4180-7272-11ea-92e6-d3d9627b27a8.png)

**Comment by nelhage** [comment]
Oh fun, it is unsurprising that submitting 400 repos via query string doesn't work, I suppose. I think the best long-term fix for this would be to switch to `POST`ing queries to the backend (we'd have to update it to support that, but that should be a small patch). You'd need to change
- [the router](https://github.com/livegrep/livegrep/blob/3bcd52d4531e61505117aa251265fc93de26d7b1/server/server.go#L351) to support `GET`
- [extractQuery](https://github.com/livegrep/livegrep/blob/3bcd52d4531e61505117aa251265fc93de26d7b1/server/api.go#L51) to look at POST bodies if the request is a POST
- [the client](https://github.com/livegrep/livegrep/blob/3bcd52d4531e61505117aa251265fc93de26d7b1/web/src/codesearch/codesearch.js#L43) to do a `POST`

I might get a chance to look at this but I can't currently promise it. I'd happily review a PR if you get nerdsniped, though.
