### ISSUE TITLE
Have codesearch exit with error code if the grpc port is already in use

### ISSUE THREAD

**Issue by staktrace** [livegrep/livegrep#262]
We run `codesearch -grpc localhost:8080` but sometimes the port 8080 is already in use (by a previously-started instance of codesearch). In this case the new instance should exit with an error, because really there's no point to continuing if it can't listen on the port. However it seems to continue running.

It looks like maybe this needs to be handled upstream in the grpc library? I took a quick look at how `codesearch` starts and builds the grpc server, which looks like it should be invoking the code [here](https://github.com/grpc/grpc/blob/882bc0343227f8aca7ba55a52da3b28b868487b4/src/cpp/server/server_builder.cc#L412). And that code looks like it allows the first port provided to fail to bind, but subsequent port bind failures shutdown the server and return null. (This is assuming the `!r` condition reflects a port bind failure, which I'm not sure of). If this is the case this is an upstream grpc bug, but I'm filing this here for now to confirm before I go further upstream.

**Comment by nelhage** [comment]
Looking at `strace` output, it looks like GRPC sets [`SO_REUSEPORT`](http://man7.org/linux/man-pages/man7/socket.7.html), which means that _both_ processes will be bound to the port and the kernel will load-balance incoming connections between them. 

It looks like we could set https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#ga40e635cf00ea7a10c71ed71c03d97f23 to disable this option. `SO_REUSEPORT` is pretty useful in a lot of situations for zero-downtime restarts and in some load-balancing situations so I'm not sure I'd want to set that argument unconditionally, but we could add a flag for it if that'd be useful to you.

**Comment by staktrace** [comment]
Oh I didn't know such a socket option existed, that's pretty neat! But yes, for our purposes it would be nice to be able to disable that.

**Comment by staktrace** [comment]
Thank you!
