### ISSUE TITLE
Clone repositories using token

### ISSUE THREAD

**Issue by williammizuta** [livegrep/livegrep#269]
We are migrating the indexer job to use Github apps. The Github app generates a token that can be used to list and clone all repositories. Currently, the `livegrep-github-reindex` already uses the token to list the repositories, but not to clone them. To allow the clone with the token, we need to run a command similar to this:

```
git clone https://x-access-token:<token>@github.com/owner/repo.git
```

Unfortunately, the repositories list API doesn't have this clone API. So we will need to change the [ssh_url](https://github.com/livegrep/livegrep/blob/master/cmd/livegrep-github-reindex/main.go#L455) data to fit to the url above.

More about the Github apps can be found here: https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/

**Comment by nelhage** [comment]
If you pass `-http` to `livegrep-github-reindex`, it will attempt to clone over HTTP using the token as a password: https://github.com/livegrep/livegrep/blob/10e2381ecbe345ef9ae87b71e38e0b43072c72cb/cmd/livegrep-github-reindex/main.go#L39

I don't believe I've tested it with github apps, so it's possible it doesn't work for that use case for some reason, but if you haven't tried that flag yet, let's start there.

**Comment by williammizuta** [comment]
I tried with the flag, but it didn't work.

Although the token is passed to the git command, the clone command has a specific syntax to add the token `https://x-access-token:<token>@github.com/owner/repo.git`. It is a kind of mix between ssh and http url.

**Comment by nelhage** [comment]
Ah, got it. I think it looks like we probably just need to set the username to `x-access-token` and then pass the token as the password (like we currently do), to make this work? Do you know if there's an easy way to detect that we have an application token and need to do that, or are we just down to adding another flag?

**Comment by williammizuta** [comment]
It is not so easy to know if we need to use the token clone command or the normal clone command. The token needs to have permission to clone the repository and not only to list the repos. So, I believe that it is easier to add a new flag to configure it.

**Comment by nelhage** [comment]
Can you check if the linked #270 fixes your problem (passing `-installation-token` to the indexer)? Lemme know if it'd help for me to publish a docker image with that branch.

**Comment by williammizuta** [comment]
Yes, it would be very helpful if there is a docker image with the change

**Comment by nelhage** [comment]
Ok, you should be able to test with `livegrep/indexer:40b55b6c81-0`

**Comment by williammizuta** [comment]
It worked. Thanks
