### ISSUE TITLE
Docker images - Cannot open /data/livegrep.idx: No such file or directory

### ISSUE THREAD

**Issue by Kadynm49** [livegrep/livegrep#275]
I am trying to follow along with the "Docker images" section of the README.md for this repo and I am having trouble with this step:

`docker run -v $(pwd):/data --network livegrep livegrep/base /livegrep/bin/codesearch -load_index /data/livegrep.idx -grpc 0.0.0.0:9999`

The first two steps run fine but this step gives `Cannot open /data/livegrep.idx: No such file or directory`

I am new to Docker so I am likely getting something wrong here, but I was expecting the directions to work correctly without any modification so I thought I would make this issue in case the instructions aren't quite right. If it is just my error then I will close the issue, but it would be nice if there was more documentation somewhere on the docker images usage to look at.

Note: I have tried this on both Windows and within Windows Subsystem for Linux 2.

**Comment by Kadynm49** [comment]
When running on WSL2 it get's to this point:
![image](https://user-images.githubusercontent.com/19209426/90672752-74c7f300-e20b-11ea-8084-e423c516a731.png)

and then it hangs. When I open another terminal and try running it again I get this:
![image](https://user-images.githubusercontent.com/19209426/90672963-d38d6c80-e20b-11ea-8cab-8d6175e72344.png)

**Comment by nelhage** [comment]
Getting to "Serving…" means the server has booted and is accepting connections (on port 9999 under that configuration).

Is there a `livegrep.idx` file in your working directory when you launch the server? If not, it means you didn't properly build an index (that's what the

`docker run -v $(pwd):/data livegrep/indexer /livegrep/bin/livegrep-github-reindex -repo livegrep/livegrep -http -dir /data`

command does).

If it is there, it seems like `-v` might be broken on your docker? I'm not very familiar with Windows or WSL to try to estimate if that's reasonable…

**Comment by Kadynm49** [comment]
Yes there is a livegrep.idx file in the working directory when launching the server. Then after it stops at "Serving..." I run 

`docker run -d --network livegrep --publish 8910:8910 livegrep/base /livegrep/bin/livegrep -docroot /livegrep/web -listen=0.0.0.0:8910`

and go to http://localhost:8910/. Then writing anything in the query gives a 500 error from the server.

**Comment by nelhage** [comment]
Is there any output from either process when you see the 500 errors?

**Comment by Kadynm49** [comment]
I am now also trying on a Ubuntu VM hosted on Azure, and I am encountering the same issue.

Running `docker run -v $(pwd):/data --network livegrep livegrep/base /livegrep/bin/codesearch -load_index /data/livegrep.idx -grpc 0.0.0.0:9999` gives 
![image](https://user-images.githubusercontent.com/19209426/90690559-c467e800-e226-11ea-8437-f9d6a5fa9e84.png)

and the same 500 errors when the front end tries to hit the server. There is no output from the server but this error is logged to the front end console

`server error 500 {"error":{"code":"internal_error","message":"Talking to backend: rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:9999: connect: connection refused\""}}`

**Comment by nelhage** [comment]
Ah, I see the problem in our instructions. I just pushed d8d0288e5a92f96b9145a6d171e56d64e41e9296 which contains updated instructions which should work -- the existing ones did not result in the nodes being properly configured to talk to each other.

**Comment by Kadynm49** [comment]
Thanks so much @nelhage, that did the trick!
