### ISSUE TITLE
Possibility of encoding filename index directly in index dump file

### ISSUE THREAD

**Issue by LINKIWI** [livegrep/livegrep#279]
In a deployment with tens of millions of lines of source code, I've noticed that the `index_filenames` step https://github.com/livegrep/livegrep/blob/7b3cccb9c9e6201fb309f72fc4d580807e65bd12/src/dump_load.cc#L496 invoked on startup with `--load_index` can take a ~couple minutes to complete, which causes the server to be unavailable during this short period of time while the index is reloaded.

I'm curious if it's feasible to precompute the filename index and encode it into the dump file so that it can be loaded more quickly on startup? Seems like it would a breaking change to the format specification but could yield performance improvements even if read into memory eagerly, i.e. without creating an mmap'd segment for it for lazy access.

I can try taking a stab at this myself, wanted to check if it's possible or even a worthwhile idea.

**Comment by nelhage** [comment]
Yeah, it should be feasible to compute the index during indexing and store it into the dump file. I think we didn't do it originally because it was plenty fast on the test cases we saw and slightly simpler not to, but I'd happily review a PR to add it to the file.
