### ISSUE TITLE
Queries containing case/lit modifiers may behave strangely if used together

### ISSUE THREAD

**Issue by tpcwang** [livegrep/livegrep#28]
livegrep always combine the line query in this order:
`out.Line = strings.TrimSpace(ops[""] + ops["case"] + regexp.QuoteMeta(ops["lit"]))`

This produces unexpected results because this can reorder a user's query. See:
https://livegrep.com/search/linux?q=hello+world
https://livegrep.com/search/linux?q=case%3Ahello+world

**Comment by nelhage** [comment]
yeah, this is kind of a known issue, and I was lazy writing that code. The backend doesn't currently have a way to communicate “this part of the string should be case-folded, but not this other part” so I basicall wrote the code assuming only one is set. Probably I should just raise an error in that case, for now.

**Comment by tpcwang** [comment]
Yes, I think an error would be more than sufficient. I tried to do it but I'm not really familiar with go's convention for error handling.

**Comment by nelhage** [comment]
OK, I think that branch should do it.

**Comment by tpcwang** [comment]
Thanks! I just tried it out and it works well.

**Comment by tpcwang** [comment]
I found out today that lit doesn't work for me any more. I think it's because of the fact that QuoteMeta was dropped during this refactored. I added a comment in the diff, but I'm not sure if that'll generate a notification, so adding the same comment here.
