### ISSUE TITLE
Clarification about index files - can they be loaded into memory?

### ISSUE THREAD

**Issue by kkom** [livegrep/livegrep#282]
Hey, I'm just playing with livegrep and I'd like to better understand the indexing process.

The docs here https://github.com/livegrep/livegrep/tree/1358b0699d382e02012d6a89003790edf552c092#using-index-files say the following:

> This has the dual advantages of allowing indexes that are too large to fit in RAM, and of allowing an index file to be reused.

What if I'm interested in the second, but not the first? I.e. persisting an index & allowing it to be shared across a cluster of codesearches, but still loading it into memory (to make codesearch queries faster)?

[The docs](https://github.com/livegrep/livegrep/tree/1358b0699d382e02012d6a89003790edf552c092#using-index-files) or [the schema](https://github.com/livegrep/livegrep/blob/1358b0699d382e02012d6a89003790edf552c092/src/proto/config.proto) don't make the behavior clear to me.

**Comment by nelhage** [comment]
codesearch doesn't have an option to pin the index into memory, but it uses `mmap` to access the index, so it should be loaded into cache if the machine has enough RAM. You could also use something like [`memlockd`](https://doc.coker.com.au/projects/memlockd/) to ensure it's kept in memory, if you wanted.

Does that answer the question?

**Comment by kkom** [comment]
It does, thank you! This is actually brilliant. Thanks for the [memlockd](https://doc.coker.com.au/projects/memlockd/) suggestion (although it doesn't look to be necessary).

I have another question on the index files, hope you don't mind me asking it here. Are the index files hot reloaded by the searcher instances? I looked through the docs and configuration file schema, but I couldn't find any info on that.

**Comment by nelhage** [comment]
The index files aren't hot-reloaded by default. If you pass `-hot_index_reload`, though, it will watch the index and attempt to reload if it notices the file change on disk. Alternately, if you run the server with `-reload_rpc`, it enables a GRPC call to ask the server to reload, which can be sent via the `livegrep-reload ` command in `cmd/…`.

**Comment by kkom** [comment]
Thanks! Not sure how I missed that option going through the docs!
