### ISSUE TITLE
File names no longer showing up

### ISSUE THREAD

**Issue by bmalehorn** [livegrep/livegrep#305]
We recently upgraded to the latest commit and found that our file names had vanished!

| before (ae31f02999) | after (186e6a6986) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3344958/129124147-abd2bb84-a935-4281-adf1-f5332d7edf98.png) | ![image](https://user-images.githubusercontent.com/3344958/129124144-6298873d-13b0-4198-bbdd-808f238f2a08.png) |

This seems to be caused by https://github.com/livegrep/livegrep/pull/303, which changed the styling on file names. Rolling back to the previous commit, ae31f02999, fixed the issue.

@danwang would you mind taking a look at this?

**Comment by danwang** [comment]
Sorry about that! I'll take a look at fixing this.

**Comment by bmalehorn** [comment]
Thanks!
