### ISSUE TITLE
How to enable source browser in livegrep frontend?

### ISSUE THREAD

**Issue by lopopolo-figma** [livegrep/livegrep#307]
Hi @nelhage it's @lopopolo 👋 I hope you're well.

I'm looking to replicate the behavior I've seen in some livegrep deployments where clicking links in the search results leads to source being shown in the livegrep frontend, which enables the highlight + `/` shortcut to continue searching within the livegrep UI shell.

I took a peek in the `server.json` schema and didn't see anything for this. Is this something I need to enable at offline indexing time to build the source into the `livegrep.idx` file?

**Comment by nelhage** [comment]
I had to read source to refresh my memory … this could definitely be cleaned up. But it turns out I answered this same question elsewhere in email, so I'll quote:

> In order to show the file view, you need to give the server the information about the repository structure from the index config. Add an `index_config` to your `server.json`, and then add the contents of `index.json` as the value. (You don't actually need the full structure, but that's the simplest option). You can see some documentation on the full server config here: https://github.com/livegrep/livegrep/blob/1358b0699d382e02012d6a89003790edf552c092/server/config/config.go#L17-L62

If you're enthusiastic about a doc change or even a code change to make this more sensible, I'd enthusiastically take it :)

**Comment by lopopolo-figma** [comment]
It looks like this feature requires a `git` executable and from what I can tell, `git` is not installed in the `livegrep/base` docker image.

**Comment by nelhage** [comment]
Yeah, that doesn't surprise me that we don't install `git` (If we did, it would probably go in the `livegrep/web` image where the frontend HTTP server runs). I'd default to leaving it out but I'd be open to adding it in if it'd make your life materially easier.
