### ISSUE TITLE
Made some changes in fork, would any be useful? 

### ISSUE THREAD

**Issue by xvandish** [livegrep/livegrep#313]
Hi, I have a few changes in my fork, and I guess before I go presumptively cherry-picking the one's that would be useful (if any) and opening a PR - I figured I'd ask if you'd like to see any of these.

1. Switched all CI to GH Actions and packaging system to GH Packages - would require some changes from `xvandish-livegrep` to `livegrep` as the package name. 
2. Allow num of pages per GH repos query (in github-live-reindexer) to be configurable (tiny change)
3. allow num of workers in github-fetch-reinfex to be configurable (also tiny change)
4. allow GH queries for repos to be concurrent at a configurable rate. For an organization with like 4k repos, saves a lot of time. ~50s 

Since some of these changes are in `main` already, but some aren't (namely concurrent requests) a PR would include the changes in main, so I'd have to cherry pick depending on what you would/wouldn't find useful.

Here's a comparison with the changes - let me know.
https://github.com/livegrep/livegrep/compare/main...xvandish:concurrent-reindexer-github-requests

I've also got a `statsd` implementation that I'll probably finish sometime soon, and I'm working on porting over/cleaning up the features that Dropbox references here (https://github.com/livegrep/livegrep/blob/d0148a0fe662d2fc10aebcbfcaac87cbeb8b17e6/web/templates/fileview.html#L85-L86) but that didn't actually get implemented (in the base repo, they are implemented in their fork) - if any of these future modifications are of interest, also let me know! Thanks.

**Comment by nelhage** [comment]
Those all sound great! (1) especially is something I've been meaning to do.

Would you be open to splitting your fork into separate PRs for each feature? I'd be happy to review them in that form.

**Comment by xvandish** [comment]
Cool, & ofc! I'll work on splitting out the feature commits onto new branches so they can by PR'd individually - & then open them up for your review.

**Comment by xvandish** [comment]
PR #314 is up for change 2

**Comment by xvandish** [comment]
PR #315 is up for changes 3 & 4.

**Comment by xvandish** [comment]
these have all been made - closing
