### ISSUE TITLE
Socket error when starting up livegrep server

### ISSUE THREAD

**Issue by abdurraheemali** [livegrep/livegrep#325]
On Windows 11, running from Ubuntu in WSL:

abduali@DESKTOP-PTNJO7O:~/livegrep$ bazel-bin/src/tools/codesearch -grpc localhost:9999 doc/examples/livegrep/index.json
Walking path_spec name=livegrep/livegrep, path=src/
  walking full tree
done
Walking repo_spec name=livegrep, path=. (including  submodules: false)
  walking HEAD
  done
Finalizing...
Building filename index...
repository indexed in 0.491455s
== begin metrics ==
index.bytes 1405588
index.bytes.dedup 1251451
index.content.chunks 1
index.content.ranges 36831
index.data.chunks 1
index.files 253
index.lines 36831
index.lines.dedup 27231
== end metrics ==
E0302 05:06:34.797868700   19041 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1646183194.797848400","description":"Protocol not available","errno":92,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
Serving...

**Comment by abdurraheemali** [comment]
Closing since this is just a bug in cpython and WSL doesn't support SO_REUSEPORT

**Comment by LINKIWI** [comment]
`SO_REUSEPORT` is a socket option only available on Linux. It would probably be a good idea to compile-guard its usage in `codesearch.cc`

**Comment by abdurraheemali** [comment]
Update: https://github.com/livegrep/livegrep/pull/263 we could modify the -reuseport option to be false in WSL/Windows

**Comment by abdurraheemali** [comment]
wait, even setting it to false still results in

abduali@DESKTOP-PTNJO7O:~/livegrep$ bazel-bin/src/tools/codesearch -grpc localhost:9999 doc/examples/livegrep/index.json
Walking path_spec name=livegrep/livegrep, path=src/
  walking full tree
done
Walking repo_spec name=livegrep, path=. (including  submodules: false)
  walking HEAD
  done
Finalizing...
Building filename index...
repository indexed in 0.252304s
== begin metrics ==
index.bytes 1405551
index.bytes.dedup 1251420
index.content.chunks 1
index.content.ranges 36829
index.data.chunks 1
index.files 253
index.lines 36829
index.lines.dedup 27230
== end metrics ==
E0311 21:16:28.899616000   11936 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1647062188.899593000","description":"Protocol not available","errno":92,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
Serving...
