### ISSUE TITLE
Regex lookaround.

### ISSUE THREAD

**Issue by benxu-stripe** [livegrep/livegrep#334]
Would it be possible to add support for regex lookahead and lookbehind?

Failing that, would it be possible to document the dialect of regex being used here?

**Comment by nelhage** [comment]
We use [re2](https://github.com/google/re2) as our regular expression engine. That's documented on [the about page](https://livegrep.com/about) and in the help text on the search page -- where else might be helpful for you to have found it?

We're unlikely to support lookahead and behind; I'm not sure that an FA-based implementation like RE2 can support them.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/16725/165426216-c47dc0fe-f7b7-42a0-96f3-d512e9c00923.png">

**Comment by benxu-stripe** [comment]
Hm, my bad. I usually skip the site itself or docs (since I've found docs to be notoriously unreliable) and go straight to source code out of force of habit. Again, my bad.

That said, it'd be nice for it to be in the README as well.

On the other hand, lookarounds can be implement by FA (assuming that means finite automata) implementations of regex, as they can be described by two additional state machines.
