### ISSUE TITLE
High-res logo?

### ISSUE THREAD

**Issue by jez** [livegrep/livegrep#337]
Is there a higher res version of the logo than the favicon.ico file that's checked into the repo?

I'm trying to make a custom emoji for use with slack 😅 

Feel free to close if the original assets have been lost or cannot be shared, thanks!

**Comment by jboning** [comment]
I don't believe there was ever any higher res version. If I
recall correctly, the favicon pixels were artisinally handcrafted in some
web bitmap editor. I expected a better logo to come along in the ensuing
five years!
