### ISSUE TITLE
Support for multiple file: or path: terms

### ISSUE THREAD

**Issue by clint-stripe** [livegrep/livegrep#378]
I often write queries that already make use of `path:foo` -- but the suggested "Narrow to filetype" buttons adds a `file:\.rb$` which is then an error.

Is there any fud with allowing multiple? I put together [a WIP attempt](https://github.com/clint-stripe/livegrep/commit/b70ed14326b4096a6fac69a655b6204d65e7694e) which...is pretty invasive :) It still needs a bit of cleanup and some additional tests if we think this seems reasonable at all 😆

**Comment by nelhage** [comment]
Hm. I feel open to it, I think. I have definitely ever wanted that feature before, and it's not trivial to fake it, since regex intersection is nontrivial to do in your head :)
