### ISSUE TITLE
Allowing a end-user-configurable soft-limit on number of match results

### ISSUE THREAD

**Issue by tpcwang** [livegrep/livegrep#44]
There are a couple of times that I wish livegrep can return more than 50 results. I know that the backend currently supports defining the maximum number of match results as a command line argument, but I think it could be beneficial to have a configurable soft-limit.

For example, I might pass max_matches=200 to the backend, and set the default soft-limit on the frontend to be 50. But if I want to look at more results, I can explicitly change the soft-limit up to 200 to see more results. This could be presented as a hidden url parameter or a drop-down box.

What are your thoughts?

**Comment by nelhage** [comment]
Yeah, I think this would make sense. We run with `max_matches=200` on the stripe.com instance, and it'd be nice to be able to reduce scope at the frontend.

I'm hoping to do a bit of work on livegrep soon, so I'll add this to the list. I'd also be happy to review a PR if you happen to get around to it.

**Comment by gnprice** [comment]
FWIW, in our fork at Dropbox we made this change -- partly because I often want more than 50 on the web, and partly because we built a small CLI and with a CLI you can really handle lots of results well and you often want them.

Here's the commit message:
```
commit b60b8fc8b01252e59c7210388f42ee36472cdfa3
Author: Greg Price <gregprice@dropbox.com>
Date:   Fri Nov 20 16:14:08 2015

    Lift max_matches limit, optionally
    
    Summary:
    This diff does three things:
    * Raise the default max_matches on the backend from 50 to 5000.
    * Add a new "max_matches" field in queries, thread it through to
      the search engine, and allow it to tighten the limit.
      This is boring but the bulk of the diff.
    * In the web frontend, set max_matches to 100.
    
    This gives more results while keeping things snappy.  Possibly
    more than 100 would be fine too; we can play with it.
    
    Asking the web UI to display 5000 results becomes very slow.
    Because we speculatively search as you type, so the first
    few characters of an intended search become a very short query
    usually with many results, this is very common.  If we can
    optimize this we might raise the web limit much higher too.
    
    The biggest immediate win is in the CLI -- we can handle
    5000 results in about a second.  So this opens up a wide range
    of searches to do comprehensively.
```

Unfortunately a quick attempt at a cherry-pick onto master just now didn't work -- that part that's "boring but the bulk of the diff" goes all through the stuff that changed in the great gRPC refactor.

Here's a cherry-pick onto upstream but a pretty old version of upstream:
https://github.com/dropbox/livegrep/commit/df1d1cec822196036d67a9dc5d2509a7a13f45e4
Perhaps that's helpful to someone in writing an up-to-date version.

**Comment by tpcwang** [comment]
That makes a lot of sense. Thanks for sharing @gnprice 

I can look into rebasing that onto the current master, provided that @nelhage agrees to the new max_matches field in queries.

**Comment by gnprice** [comment]
@tpcwang Sounds like a plan!

My reading of @nelhage 's reply above, FWIW, is that he's already on board with your general approach -- so I'd suggest just going ahead and writing the PR (including a rebase of that old commit I pushed if that's helpful) and sending it for review. :)

**Comment by nelhage** [comment]
Yep, ditto @gnprice's comment. I'd happily take a rebase of that commit, and might get around to implementing it myself but can't promise a timeline.
