### ISSUE TITLE
Search across several repos, or in one user-chosen repo

### ISSUE THREAD

**Issue by gnprice** [livegrep/livegrep#60]
At Dropbox like at probably most organizations, we have a number of different repos -- a few big ones (one for most server code, one for the desktop client, etc.), and various miscellaneous ones that don't belong in those or we just haven't gotten around to merging in.

Our internal livegrep instance searches across all of our major repos and some minor ones. There's another, entirely in-house, code-search tool that searches across just one repo at a time, with a big ol' dropdown to choose which one you want.

I'm often searching to convince myself that something isn't used anymore or some bad pattern doesn't exist, or to find out *where* something is referred to from, like when some code is clearly being invoked and I can't tell how. So I really like having comprehensive search across all the repos related to a project, which is why I built our internal livegrep instance that way.

But it can also get kind of noisy, especially in navigational searches when you're trying to type just a minimal quick pattern (with the power of search-as-you-type!) to find the thing you have in mind, and you know perfectly well which repo it's in. Especially if your work is almost always in a particular repo; which for many people it is, especially so at a company that does a good job of the "monorepo" pattern that Google and Facebook are well known for and Dropbox successfully mostly moved to in 2014 and 2015, where e.g. all your web apps and backend services (and maybe more things) are seamlessly source-controlled together. So the desire to search just one repo is a pretty common reason that users give for preferring the other tool. And we're about evenly split on users who prefer that tool vs. our livegrep instance, so that's a lot of users with that preference.

Crucially, if the last time you used that other tool you searched repository X, then the next time you go to its front page and just type a quick query, you'll get a search over repository X.

I'm not sure how to integrate this well with Livegrep's UI and the all-repos search that I also value. So this is a less concrete feature request than usual. Ideas?

**Comment by alexmv** [comment]
https://chmrr.net/repos/ presents one possible UI to resolve this.  It has the following features:
 - Saves the last setting in a cookie.
 - Supports searching sets of repositories easily.
 - The state "all repositories" will expand to include new repositories as they are added, but a state of fewer than all repositories will not.
 - Searching one repository is tab, type, enter.

However, this comes at the cost of ~500k of JS, as it includes both jQuery and Bootstrap.  While all of that should be cached after the first load, it is a notable departure from the current amount of UI overhead.  What is livegrep's stance on keeping its interface as JS-light as possible?

**Comment by gnprice** [comment]
I like that UI! Thanks for making the mockup. There are small tweaks I'd make, but if this were integrated straight into livegrep (preserving typeahead-search, and with the main query box focused initially so you can just type and get results), that'd be a great advance already and we can iterate on the details.

> However, this comes at the cost of ~500k of JS, as it includes both jQuery and Bootstrap. While all of that should be cached after the first load, it is a notable departure from the current amount of UI overhead. What is livegrep's stance on keeping its interface as JS-light as possible?

My own inclination would be that using some libraries at that scale is fine. Alternatively if @nelhage wants to keep a tight lid on it, I'm sure this functionality can be implemented without most of that -- it'll just be more effort (as will most interesting frontend work, I imagine.)

**Comment by nelhage** [comment]
I'm fine with throwing in that scale of libraries. I think it's plausible we should invest in a proper js build toolchain so we can stamp assets and so on for better caching, but I'm fine pulling in more dependencies.

**Comment by alexmv** [comment]
Do you have thoughts about attempting to use https://github.com/dropbox/rules_node to pull in the deps from npm and build via webpack -- or just vendor in a few specific files as we're currently doing?

**Comment by nelhage** [comment]
No particularly strong feelings, but I certainly like in the abstract the idea of pulling in a real frontend build toolchain that makes it easy to pull in npm deps and properly package the javascript and so on. I haven't looked at the state of the art in bazel+node rules in a while to have concrete input on the approach offhand.

**Comment by jboning** [comment]
Assuming the additional thirdparty deps are not too large, my vote is not to block on a frontend build toolchain. If it's not working after some brief experimentation, vendor what we need and file a separate issue for cleanup.
