### ISSUE TITLE
All livegrep search result links are "/null"

### ISSUE THREAD

**Issue by brandon-rhodes** [livegrep/livegrep#84]
When I back up to b459d1f the livegrep README instructions work fine, but when I advance to the next master commit 051b043 then the service, when run using the same README instructions, presents search rules that when moused over all offer only the link http://localhost:8910/null instead.

**Comment by jboning** [comment]
It looks like it's hitting this case: https://github.com/livegrep/livegrep/blob/master/web/htdocs/assets/js/codesearch_ui.js#L69

I don't yet see how #79 would have changed this. Will keep digging.
